### ISSUE TITLE
Worldborder disappears

### ISSUE THREAD

**Issue by DrakenRolle** [docwhomc/WorldBorder#3]
***Instructions***
*Prior to submitting this bug report:*
*1. Please confirm that this bug report is not a duplicate of an existing bug report.*
*2. Please confirm that you have filled out all applicable parts of the bug report.*
*3. Please confirm that you have entered `N/A` under sections that are not applicable.*
*4. Please confirm that you have removed all example text and instructions (including this section), which is distinguished from other text with italics.*

**Describe the bug**
World Border gets deleted after reload/restart

**To Reproduce**
*Steps to reproduce the behavior:*
*1. Set Worldborder
*2. Reload Server
*3. Check Worldborder
*4. Worldborder is gone

**Expected behavior**
Worldborder should be still exist/ get loaded again form storage after reload

**Screenshots**
*If applicable, add screenshots to help explain your problem.
Otherwise, replace this and the prior sentence with `N/A`.*

**System and Version Info:**
 - Paper-131
 - Worldborder Version v2.0.0-dev-20w31b

**Additional context**
Using Dynmap & Dynmap Towny if relevant

**Log Files**
[23:25:25 ERROR]: Error occurred while enabling WorldBorder v2.0.0-dev-20w31b (Is it up to date?)
java.lang.IllegalArgumentException: No enum alias com.wimbli.WorldBorder.BorderData.Shape.null
at com.wimbli.WorldBorder.BorderData$Shape.fromString(BorderData.java:79) ~[?:?]
at com.wimbli.WorldBorder.Config.load(Config.java:688) ~[?:?]
at com.wimbli.WorldBorder.WorldBorder.onEnable(WorldBorder.java:23) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:932) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.Bukkit.reload(Bukkit.java:688) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[23:25:25 INFO]: [WorldBorder] Disabling WorldBorder v2.0.0-dev-20w31b

**Comment by docwhomc** [comment]
Please follow the instructions when submitting issues.
Please note that inclusion of the full version number is required (you left out the commit ID portion).

**Comment by docwhomc** [comment]
I'm going to go ahead and close this since it was resolved in [pre-release 2.0.0-dev-20w32a](https://github.com/docwhomc/WorldBorder/releases/tag/2.0.0-dev-20w32a).
